In [58]:
import pandas as pd
import numpy as np
import random
import time
import string

random.seed(time.time())

def get_name():
    name_letters = random.sample(string.ascii_letters + string.digits,6)
    return "".join(name_letters)

def get_GPA():
    gpa = random.uniform(2,5)
    return round(gpa,2)

def get_stuNum():
    header = "632007"
    tail = random.sample(string.digits,6)
    return header + "".join(tail)

def get_score():
    return random.randint(0,100)

data = {
    "姓名":[get_name() for _ in range(50)],
    "学号":[get_stuNum() for _ in range(50)],
    "GPA":[get_GPA() for _ in range(50)],
    "C语言":[get_score() for _ in range(50)],
    "OS":[get_score() for _ in range(50)],
    "DataStructure":[get_score() for _ in range(50)],
}

ts = pd.DataFrame(data,index = [ x + 1 for x in range(50)])
ts = ts.rename(index = lambda x : 2*x +3,columns={"C语言":"wocao"})
print(ts )

         姓名            学号   GPA  wocao  OS  DataStructure
5    3Py6sw  632007394572  3.75     43  56             15
7    DJZTxN  632007985673  4.45     37  63             89
9    Q9wcdv  632007348169  2.61      1  38             30
11   HbcOQ1  632007940186  3.18     15  30             77
13   GohzlQ  632007785326  2.73     97  80             41
15   mx5Dlr  632007432790  4.04     82  51             19
17   R5D0Sc  632007078132  2.88     79  55             99
19   jvBJuU  632007357416  4.20     93  39             47
21   CyIFR4  632007273059  2.67     82   5             48
23   Uxz6wD  632007406398  3.81      4   2              7
25   V7H9Cb  632007637809  2.53     82  21             32
27   GLHsCN  632007182364  4.25     98   1             18
29   NRV80b  632007527618  2.81     93  22             28
31   nFC09f  632007013947  3.04     16   2              9
33   FgwJmx  632007835204  4.31     21  98             30
35   J6moGz  632007247813  4.32     98  38             83
37   RjcIWN  6

In [64]:
import  numpy as np
import  random

arr1 = np.arange(25).reshape(5,5)
arr2 = np.random.randint(0,100,size=(5,5))
print(np.concatenate([arr1,arr2],axis=1))

[[ 0  1  2  3  4 95 83  8 49 29]
 [ 5  6  7  8  9 61 78 39 58 85]
 [10 11 12 13 14 34 74 79 99 49]
 [15 16 17 18 19 19 97 38 88 81]
 [20 21 22 23 24 54 46 30  7 36]]


In [ ]:
from datetime import  datetime


date_list = [
    datetime(2019,3,4,9,3)
]

In [ ]:
from seaborn import sns
