In [1]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
],dtype = np.int64)
print(arr.reshape(3,2).ndim)
print(arr.flags)


2
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [2]:
import numpy as np

matrix = np.empty((2,4),dtype= np.uint8)
print(matrix)

[[  0   0 128  63]
 [  0   0 128  63]]


In [3]:
import numpy as np

arr = np.arange(10,30,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28]


In [4]:
import numpy as np
import random

list = [[random.randint(0,100) for _ in range(5)] for _ in range(5)]

arr = np.array(list)
print(arr)

[[86 67 45 40 31]
 [48 41 99 26 85]
 [87 84 52 14 59]
 [98 85 32 13 92]
 [38 98 70 94 60]]


In [5]:
import numpy as np

matrix = np.random.randint(0,100,(5,5))
