In [33]:
import pickle
import numpy as np

arrOne = np.random.randint(0,100,size=10)
arrTwo = np.random.randint(0,100,size=10)
arrThree = np.random.randint(0,100,size= 10)
np.savez("myArr",a = arrOne,b = arrTwo,c = arrThree)

In [38]:
arr   = np.load("./myArr.npz")
print(arr['b'])

[64 69 79 41  4 39 39 83 42 55]


In [43]:
A = np.random.randint(0,1000,size = (5,5))
B = np.random.randint(0,1000,size = (5,5))

print(A)
print(B)
print()

[[444 510  32 787  36]
 [276 978 827 140 593]
 [392 856 201  53 520]
 [162 255 961 375 673]
 [446 308 395 656 819]]
[[573 671 169 721 913]
 [604 145  48 809  47]
 [339 890 581 261 127]
 [440 164 514 864 789]
 [234 139 467 872 615]]
[[254412 342210   5408 567427  32868]
 [166704 141810  39696 113260  27871]
 [132888 761840 116781  13833  66040]
 [ 71280  41820 493954 324000 530997]
 [104364  42812 184465 572032 503685]]
